### ISSUE TITLE
How to set up severity in the text corruption function `generate_textflint`?

### ISSUE THREAD

**Issue by chenxshuo** [Maddy12/VideoLanguageModelRobustness#1]
Hi there, thank you for your great work and repo! 

I wonder how I should set up the corruption severity in text corruption, specifically, in the function `generate_textflint` [link](https://github.com/Maddy12/VideoLanguageModelRobustness/blob/master/generate_noisy_text.py#L346). 

I was unable to locate the severity settings and am curious about how you designated the different severity levels. Alternatively, it's possible that different severities were not tested for text corruptions since I also could not find any relevant descriptions in the paper.

Many thanks and looking forward to your reply! 😄

**Comment by Maddy12** [comment]
In this work, there are no severity levels for text. However this is a great research direction if you are able to implement different severities. We attempted to measure how severe the perturbations were by measuring the perplexity of each perturbation, this is shown in the Supplementary matrials. 

Hope this helps!
